apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        fsGroup: 1000  # Define el grupo de archivos para permisos
      initContainers:
      - name: init-wordpress
        image: wordpress:latest
        command: ["sh", "-c", "chown -R 1000:1000 /var/www/html"]
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "ip-172-31-81-180.ec2.internal"
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpressuser
        - name: WORDPRESS_DB_PASSWORD
          value: password
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: true
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim  # Asegúrate de que coincida con el PVC

