apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-nfs-pv-new
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/moodle
    server: 3.91.18.58
