apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs
parameters:
  server: 172.31.91.122
  path: /srv/nfs/moodledata
  readOnly: "false"
mountOptions:
  - hard
  - nfsvers=4  # Especifica la versión de NFS si es necesario
  - rw

